name: Testing-vault



on:
    push:
      branches: [main]
jobs:
    testing-vault:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Dump OIDC token claims
              uses: github/actions-oidc-debugger@v1
            - name: hashicorp-test
              uses: hashicorp/vault-action@v3
              with:
               url: http://54.205.102.151:8200
               jwtGithubAudience: femi
               method: jwt
               tlsSkipVerify: true
               role: femi-test-role
               secrets: |
                secret/data/apikeys deploymentServer | DEPLOYMENT_KEY

  

